# Generated by Django 4.2.2 on 2023-08-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_stream_user_stream"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stream",
            options={"verbose_name": "Поток", "verbose_name_plural": "Потоки"},
        ),
    ]
