# Generated by Django 4.2.2 on 2023-07-13 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0002_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="curator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_curator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="curator_response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
