# Generated by Django 4.2.2 on 2023-07-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_comment_curator_comment_curator_response"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="files",
        ),
        migrations.AddField(
            model_name="comment",
            name="is_student_comment",
            field=models.BooleanField(default=True),
        ),
    ]
