# Generated by Django 4.2.2 on 2023-08-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_comment_parent_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent_comment",
        ),
    ]
