# Generated by Django 4.2.2 on 2023-09-19 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_remove_lesson_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0009_alter_comment_curator_alter_comment_lesson_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.lesson"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
