# Generated by Django 4.2.2 on 2023-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AviationCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="stransit_course_images"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("online", "Онлайн"), ("offline", "Офлайн")],
                        default="offline",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("about_course", models.TextField(max_length=300)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndustrialCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="stransit_course_images"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("online", "Онлайн"), ("offline", "Офлайн")],
                        default="offline",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("about_course", models.TextField(max_length=300)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OnlineCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="stransit_course_images"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("online", "Онлайн"), ("offline", "Офлайн")],
                        default="offline",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("about_course", models.TextField(max_length=300)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
