# Generated by Django 4.2.2 on 2023-08-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stransit", "0002_alter_aviationcourses_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.PositiveIntegerField(null=True)),
                ("message", models.TextField(max_length=500)),
            ],
            options={
                "verbose_name": "Новая заявка",
                "verbose_name_plural": "Новые заявки",
            },
        ),
    ]
