# Generated by Django 4.2.2 on 2023-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stransit", "0003_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
