# Generated by Django 4.2.2 on 2023-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stransit", "0004_alter_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
