# Generated by Django 4.2.2 on 2023-08-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stransit", "0005_contact_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
