# Generated by Django 4.2.2 on 2023-09-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stransit", "0006_contact_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.IntegerField(null=True),
        ),
    ]
