# Generated by Django 4.2.2 on 2023-12-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stransit', '0008_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviationcourses',
            name='about_course',
            field=models.TextField(max_length=1100, verbose_name='О курсе'),
        ),
        migrations.AlterField(
            model_name='aviationcourses',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='industrialcourses',
            name='about_course',
            field=models.TextField(max_length=1100, verbose_name='О курсе'),
        ),
        migrations.AlterField(
            model_name='industrialcourses',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='onlinecourses',
            name='about_course',
            field=models.TextField(max_length=1100, verbose_name='О курсе'),
        ),
        migrations.AlterField(
            model_name='onlinecourses',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Название курса'),
        ),
    ]
