# Generated by Django 4.2.2 on 2024-03-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stransit", "0009_alter_aviationcourses_about_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviationcourses",
            name="time",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Продолжительность курса",
            ),
        ),
        migrations.AddField(
            model_name="industrialcourses",
            name="time",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Продолжительность курса",
            ),
        ),
        migrations.AddField(
            model_name="onlinecourses",
            name="time",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Продолжительность курса",
            ),
        ),
    ]
