# Generated by Django 4.2.2 on 2023-08-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_alter_schedule_weekdays"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "Расписания", "verbose_name_plural": "Расписание"},
        ),
    ]
