# Generated by Django 4.2.2 on 2023-06-27 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"verbose_name": "Модуль", "verbose_name_plural": "Модули"},
        ),
    ]
