# Generated by Django 4.2.2 on 2023-07-05 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=155, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=155, null=True),
                ),
                (
                    "time",
                    models.PositiveIntegerField(blank=True, default=90, null=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_type_images"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип курса",
                "verbose_name_plural": "Типы курсов",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.coursetype",
            ),
        ),
    ]
