# Generated by Django 4.2.2 on 2023-07-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_category_alter_course_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.course",
            ),
        ),
    ]
