# Generated by Django 4.2.2 on 2023-07-10 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0006_alter_module_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="curators",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
