# Generated by Django 4.2.2 on 2023-07-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_lesson_zoom_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="learn_documentation",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
