# Generated by Django 4.2.2 on 2023-08-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_alter_lesson_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
