# Generated by Django 4.2.2 on 2023-08-26 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0015_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="students",
            field=models.ManyToManyField(
                related_name="notifications", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
