# Generated by Django 4.2.2 on 2023-08-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_alter_notification_options_lesson_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
    ]
