# Generated by Django 4.2.2 on 2023-12-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
