# Generated by Django 4.2.2 on 2024-03-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0019_alter_course_title_alter_coursetype_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
