# Generated by Django 4.2.2 on 2024-06-08 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0021_alter_module_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
