# Generated by Django 4.2.2 on 2023-06-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_test_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={
                "verbose_name": "Тестовый вопрос",
                "verbose_name_plural": "Тестовые вопросы",
            },
        ),
        migrations.AlterModelOptions(
            name="testchoice",
            options={"verbose_name": "Ответ", "verbose_name_plural": "Ответы"},
        ),
    ]
