# Generated by Django 4.2.2 on 2023-07-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_test_score_alter_testchoice_is_correct_testresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
