# Generated by Django 4.2.2 on 2023-07-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0005_testresult_attempts_alter_testresult_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="testchoice",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
