# Generated by Django 4.2.2 on 2023-07-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0006_testchoice_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="user",
        ),
    ]
