# Generated by Django 4.2.2 on 2023-07-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0007_remove_test_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="score",
        ),
    ]
