# Generated by Django 4.2.2 on 2023-07-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0008_remove_test_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresult",
            name="score",
        ),
    ]
