# Generated by Django 4.2.2 on 2023-07-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0009_remove_testresult_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
