# Generated by Django 4.2.2 on 2023-07-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0010_testresult_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testchoice",
            name="score",
        ),
    ]
