# Generated by Django 4.2.2 on 2023-07-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0011_remove_testchoice_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="testchoice",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
