# Generated by Django 4.2.2 on 2023-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0012_testchoice_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="question_image",
            field=models.ImageField(blank=True, null=True, upload_to="test_images/"),
        ),
        migrations.AddField(
            model_name="testchoice",
            name="choice_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="test_choice_images/"
            ),
        ),
    ]
