# Generated by Django 4.2.2 on 2023-06-27 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("essays", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="essay",
            options={"verbose_name": "Эссе", "verbose_name_plural": "Эссе"},
        ),
        migrations.AddField(
            model_name="essay",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
