# Generated by Django 4.2.2 on 2023-07-21 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_lesson_zoom_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("essays", "0003_essayresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssaySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("essay_text", models.TextField()),
                (
                    "files",
                    models.FileField(
                        blank=True, null=True, upload_to="essay_submissions/"
                    ),
                ),
                ("is_passed", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.lesson"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сдача эссе",
                "verbose_name_plural": "Сдачи эссе",
            },
        ),
        migrations.DeleteModel(
            name="EssayResult",
        ),
    ]
